#!/bin/sh
#####################################################################################################################################

# Uninstall old versions
echo "Checking for older packages..."
for pkg in docker.io docker-doc docker-compose docker-compose-v2 podman-docker containerd runc; do sudo apt-get remove $pkg; done

#####################################################################################################################################

# Install using the apt repository
echo "Set up Docker's apt repository."
# Add Docker's official GPG key:
sudo apt-get update
sudo apt-get install ca-certificates curl
sudo install -m 0755 -d /etc/apt/keyrings
sudo curl -fsSL https://download.docker.com/linux/ubuntu/gpg -o /etc/apt/keyrings/docker.asc
sudo chmod a+r /etc/apt/keyrings/docker.asc

# Add the repository to Apt sources:
echo \
  "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu \
  $(. /etc/os-release && echo "$VERSION_CODENAME") stable" | \
  sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
sudo apt-get update

#####################################################################################################################################

# Installing latest docker package
echo "Installing latest docker package"
sudo apt-get install docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin docker-compose
echo "Installation complete, proceeding to post installation steps".

#####################################################################################################################################

# Post Installation steps
# Create the docker group.
echo "Creating docker group"
sudo groupadd docker

# Add your user to the docker group.
echo "Adding current user '$USER' to docker group"
sudo usermod -aG docker $USER

#####################################################################################################################################

# Configure Docker to start on boot with systemd
echo "Configuring docker to start on boot with systemd"
sudo systemctl enable docker.service
sudo systemctl enable containerd.service

#####################################################################################################################################

# Ask user to logout to reflect the changes
echo "Now logout of the terminal/system to make changes persistant."
